<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBn4w1x\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBn4w1x/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXBn4w1x.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXBn4w1x\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXBn4w1x\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XBn4w1x',
    'container.build_id' => '861c35ac',
    'container.build_time' => 1538783385,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBn4w1x');
