<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWx9qA1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWx9qA1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWWx9qA1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWWx9qA1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWWx9qA1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WWx9qA1',
    'container.build_id' => '0c583485',
    'container.build_time' => 1538783860,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWx9qA1');
