<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container09YLK4P\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container09YLK4P/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container09YLK4P.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container09YLK4P\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container09YLK4P\srcDevDebugProjectContainer(array(
    'container.build_hash' => '09YLK4P',
    'container.build_id' => 'a3e26531',
    'container.build_time' => 1538781534,
), __DIR__.\DIRECTORY_SEPARATOR.'Container09YLK4P');
